stages:
  nb-to-py:
    cmd: bash convert.sh
    deps:
      - expCNN.ipynb
      - gridsearch_dvc.ipynb
    outs:
      - expCNN.py
      - gridsearch_dvc.py
  run-experiments:
    cmd: python expCNN.py
    deps:
      - expCNN.py
      - params.yaml
    outs:
      - metrics.txt
      - cm.png
    metrics:
      - metrics.json:
          cache: false
