name: check_pipe
on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: run pipe
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global --add safe.directory /__w/Practice-experiments/Practice-experiments
            pip install -r require.txt
            bash convert.sh
            
            dvc exp remove --all --queue
            dvc exp run --queue --set-param train.epochs=10 --set-param model.layers=1 --set-param model.dropout=0.1
            #python gridsearch_dvc.py
            #dvc exp run --run-all
            
            echo "## Experiments" >> report.md
            #dvc exp show -A --md >> report.md
  
            cml send-comment report.md
